chart:
  targetRevision: 0.0.40
kargo:
  warehouse:
    chart:
      repoURL: https://prometheus-community.github.io/helm-charts
      name: kube-prometheus-stack
      semverConstraint: ^75.0.0
  stages:
    dev:
      enabled: false
    pro:
      enabled: false
    core:
      enabled: true
extSecrets:
  - name: github-ssh
    namespace: addon-coredns
    labels:
      kargo.akuity.io/cred-type: git
    secrets:
      - secretKey: repoURL
        remoteRef:
          key: secret/kargo/github
          property: repo_url
      - secretKey: sshPrivateKey
        remoteRef:
          key: secret/kargo/github
          property: ssh_private_key