vault:
  server: http://vault.vault.svc.cluster.local:8200
  auth:
    appRole:
      roleId: 0370b1d1-46ce-5239-dfbd-66f738d95a7c
      secretRef:
        name: vault-approle-secret
        key: secret-id
        namespace: default
  caProvider:
    name: home-internal-root-ca