image:
  tag: 1.0.2

deployment:
  containerPort: 5000

  oidc:
    enabled: true

  additionalEnv:
    WARRACKER_MEMORY_MODE: ultra-light
    WARRACKER_NOTIFICATION_ENABLED: "false"
    FLASK_ENV: "production"
    FRONTEND_URL: "https://warracker-dev.internal"

ingress:
  enabled: true
  host: warracker-dev.internal