ingress:
  annotations:
    cert-manager.io/cluster-issuer: home-internal-ca-issuer
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    - hosts:
        - romm.internal
      secretName: romm-internal-tls