global:
  image:
    tag: 2025.8.4

authentik:
  postgresql:
    user: secrets+literal://vals!ref+vault://secret/authentik/development/postgres#/username
    password: secrets+literal://vals!ref+vault://secret/authentik/development/postgres#/password

server:
  ingress:
    hosts:
      - auth-dev.internal.org

  envFrom:
    - secretRef:
        name: authentik-env

  resources:
    requests:
      cpu: 350m
      memory: 400Mi
    limits:
      cpu: 500m
      memory: 512Mi

worker:
  envFrom:
    - secretRef:
        name: authentik-env

  resources:
    requests:
      cpu: 350m
      memory: 400Mi
    limits:
      cpu: 500m
      memory: 512Mi