global:
  image:
    tag: 2025.8.4

authentik:
  postgresql:
    user: secrets+literal://vals!ref+vault://secret/authentik/development/postgres#/username
    password: secrets+literal://vals!ref+vault://secret/authentik/development/postgres#/password

deployment:
  additionalEnv:
    PAPERLESS_URL: "https://paperless-dev.internal"

server:
  ingress:
    hosts:
      - auth-dev.internal.org

  envFrom:
    - secretRef:
        name: authentik-env

  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

worker:
  envFrom:
    - secretRef:
        name: authentik-env

  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi