apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: warracker-trusted-ca
  namespace: warracker
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: warracker-trusted-ca
    template:
      type: Opaque
    creationPolicy: Owner
  data:
    - secretKey: tls.crt
      remoteRef:
        key: secret/cert-manager/root-ca
        property: tls.crt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: warracker-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: warracker-db
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.deployment.envSecretKeys.postgres }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.deployment.envSecretKeys.postgres }}
        property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: warracker-oidc-es
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: warracker-oidc
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: {{ .Values.deployment.envSecretKeys.oidc }}
        property: client_id
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.deployment.envSecretKeys.oidc }}
        property: client_secret
