apiVersion: v1
kind: PersistentVolume
metadata:
  name: warracker-uploads-pv
  labels:
    app: warracker
    type: uploads
spec:
  capacity:
    storage: {{ .Values.pvc.uploads.storage | default "5Gi" }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: {{ .Values.pvc.uploads.storagePath }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warracker-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  selector:
    matchLabels:
      app: warracker
      type: uploads
  resources:
    requests:
      storage: {{ .Values.pvc.uploads.storage }}
