apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote
  namespace: {{ .Values.kargo.project.name }}
spec:
  vars:
  - name: chart
    value: {{ .Values.kargo.warehouse.chart.repoURL }}
  {{- if .Values.kargo.warehouse.image.repoURL }}
  - name: image
    value: {{ .Values.kargo.warehouse.image.repoURL }}
  {{- end }}
  - name: repoURL
    value: git@github.com:Squallium/kubernetes-at-home.git
  - name: branch
    value: main
  - name: chartValuesPath
  - name: valuesPath
  - name: argocdApp
  steps:
  - uses: git-clone
    config:
      repoURL: ${{`{{ vars.repoURL }}`}}
      checkout:
      - branch: ${{`{{ vars.branch }}`}}
        path: ./out
  # update the chart version
  - uses: yaml-update
    as: update-chart
    config:
      path: ./out/${{`{{ vars.chartValuesPath }}`}}/config.yaml
      updates:
        - key: chart.targetRevision
          value: {{ printf "${{ chartFrom( vars.chart, \"%s\", warehouse(\"%s\") ).Version }}" .Values.kargo.warehouse.chart.name .Values.kargo.project.name }}
  - uses: git-commit
    as: commit-chart
    config:
      path: ./out
      message: ${{`{{ task.outputs['update-chart'].commitMessage }}`}}
  {{- if .Values.kargo.warehouse.image.repoURL }}
  # update the image version
  - uses: yaml-update
    as: update-image
    config:
      path: ./out/${{`{{ vars.valuesPath }}`}}/values.yaml
      updates:
      - key: image.tag
        value: {{ printf "${{ imageFrom( vars.image, warehouse(\"%s\") ).Tag }}" .Values.kargo.project.name }}
  - uses: git-commit
    as: commit-image
    config:
      path: ./out
      message: ${{`{{ task.outputs['update-image'].commitMessage }}`}}
  {{- end }}
  - uses: git-push
    config:
      path: ./out
  - uses: argocd-update
    config:
      apps:
      - name: ${{`{{ vars.argocdApp }}`}}
{{- if .Values.kargo.config.enabled }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-config
  namespace: {{ .Values.kargo.project.name }}
spec:
  vars:
    - name: chart
      value: {{ .Values.kargo.config.warehouse.chart.repoURL }}
    - name: repoURL
      value: git@github.com:Squallium/kubernetes-at-home.git
    - name: branch
      value: main
    - name: chartValuesPath
    - name: valuesPath
    - name: argocdApp
  steps:
    - uses: git-clone
      config:
        repoURL: ${{`{{ vars.repoURL }}`}}
        checkout:
          - branch: ${{`{{ vars.branch }}`}}
            path: ./out
    # update the chart version
    - uses: yaml-update
      as: update-chart
      config:
        path: ./out/${{`{{ vars.chartValuesPath }}`}}/config.yaml
        updates:
          - key: chart.targetRevision
            value: {{ printf "${{ chartFrom( vars.chart, \"%s\", warehouse(\"%s-config\") ).Version }}" .Values.kargo.config.warehouse.chart.name .Values.kargo.project.name }}
    - uses: git-commit
      as: commit-chart
      config:
        path: ./out
        message: ${{`{{ task.outputs['update-chart'].commitMessage }}`}}
    - uses: git-push
      config:
        path: ./out
    - uses: argocd-update
      config:
        apps:
          - name: ${{`{{ vars.argocdApp }}`}}
{{- end }}
