ingress:
  hostname: paperless.internal

deployment:
  additionalEnv:
    PAPERLESS_CSRF_TRUSTED_ORIGINS: https://paperless.internal
  oidc:
    enabled: true
    logoutRedirectUrl: https://paperless.internal/application/o/paperless/end-session/
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 3000m
      memory: 3Gi