apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: romm-db
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.envSecretKeys.postgres }}
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.envSecretKeys.postgres }}
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm-config
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: romm-config
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: PBW_ENCRYPTION_KEY
      remoteRef:
        key: {{ .Values.envSecretKeys.config }}
        property: encryption_key
