apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-trusted-ca
  namespace: paperless
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: paperless-trusted-ca
    template:
      type: Opaque
    creationPolicy: Owner
  data:
    - secretKey: tls.crt
      remoteRef:
        key: secret/cert-manager/root-ca
        property: tls.crt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: paperless-db
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: PAPERLESS_DBUSER
      remoteRef:
        key: {{ .Values.deployment.envSecretKeys.postgres }}
        property: username
    - secretKey: PAPERLESS_DBPASS
      remoteRef:
        key: {{ .Values.deployment.envSecretKeys.postgres }}
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-oidc
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: paperless-oidc
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: PAPERLESS_SOCIALACCOUNT_PROVIDERS
      remoteRef:
        key: {{ .Values.deployment.envSecretKeys.oidc }}
        property: providers
