kargo:
  project:
    name: placeholder
  warehouse:
    image:
      repoURL: ''
      semverConstraint: ''
      allowTags: ''
      ignoreTags: []
    chart:
      repoURL: placeholder
      name: placeholder
      discoveryLimit: 10
      semverConstraint: ''
extSecrets:
  - name: env
    namespace: kargo
    labels: {}
    templateType: Opaque
    secrets:
      - secretKey: secret-key
        remoteRef:
          key: placeholder
          property: placeholder
