kargo:
  project:
    name: placeholder
  warehouse:
    enabled: true
    image:
      repoURL: ''
      semverConstraint: ''
      allowTags: ''
      ignoreTags: []
    chart:
      repoURL: placeholder
      name: placeholder
      discoveryLimit: 10
      semverConstraint: ''
  stages:
    dev:
      enabled: true
      color: green
      configColor: yellow
      onlyConfig: false
      relPath: /development
      argoCDAppSuffix: -development
    pro:
      enabled: true
      color: red
      configColor: black
      onlyConfig: false
      relPath: /production
      argoCDAppSuffix: -production
    core:
      enabled: false
      color: "#a62e98"
      configColor: blue
      onlyConfig: false
      relPath: ""
      argoCDAppSuffix: ""
      requestedFreightDirect: false
  config:
    enabled: false
    warehouse:
      chart:
        repoURL: https://squallium.github.io/kubernetes-at-home
        name: placeholder
        discoveryLimit: 10
        semverConstraint: ''
  promotionTasks:
    imageVersion:
      tagKey: image.tag
extSecrets:
  - name: env
    namespace: kargo
    labels: {}
    templateType: Opaque
    secrets:
      - secretKey: secret-key
        remoteRef:
          key: placeholder
          property: placeholder
