apiVersion: v1
kind: Service
metadata:
  name: pgbackweb
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.deployment.containerPort }}
  selector:
    app: pgbackweb
