deployment:
  image: ghcr.io/sassanix/warracker/main:0.10.1.12

  oidc:
    enabled: true
    issuerUrl: https://auth.internal.org/application/o/warracker/

  additionalEnv:
    WARRACKER_MEMORY_MODE: ultra-light
    WARRACKER_NOTIFICATION_ENABLED: "false"
    FLASK_ENV: "production"
    FRONTEND_URL: "https://warracker.internal"
    CURL_CA_BUNDLE: "/ca/root-ca.crt"
    SSL_CERT_FILE: "/ca/root-ca.crt"

  envSecretKeys:
    postgres: secret/warracker/production/postgres
    oidc: secret/warracker/production/authentik

ingress:
  enabled: true
  host: warracker.internal