apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-trusted-ca
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: home-assistant-trusted-ca
    template:
      type: Opaque
    creationPolicy: Owner
  data:
    - secretKey: tls.crt
      remoteRef:
        key: secret/cert-manager/root-ca
        property: tls.crt