ingress:
  hostname: paperless-dev.internal

deployment:
  additionalEnv:
    PAPERLESS_CSRF_TRUSTED_ORIGINS: https://paperless-dev.internal
  oidc:
    enabled: true
    logoutRedirectUrl: https://paperless-dev.internal/application/o/paperless/end-session/