image:
  repository: ghcr.io/sassanix/warracker/main
  tag: 0.10.1.12

deployment:
  replicas: 1
  containerPort: 80

  oidc:
    enabled: false
    providerName: authentik
    issuerUrl: https://auth-dev.internal.org/application/o/warracker/
    scope: openid email profile

  additionalEnv:
    WARRACKER_MEMORY_MODE: ultra-light
    WARRACKER_NOTIFICATION_ENABLED: "false"

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  envSecretKeys:
    postgres: secret/warracker/development/postgres
    oidc: secret/warracker/development/authentik

service:
  servicePort: 80

ingress:
  enabled: false
  proxyBodySize: "100m"
  annotations: {}
  tls: []

pvc:
  uploads:
    storage: 1Gi
    storagePath: /mnt/services/warracker/uploads

postgresql:
  image: postgres:17.3-alpine
  database: warracker
  port: 5432
  storage: 1Gi
  storagePath: /mnt/services/warracker/postgres
