apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: cloudflared
    template:
      type: Opaque
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: {{ .Values.extSecretsKeys.token }}
        property: token